version: '2.1'

services:
  camera-stream:
    build: ./camera-stream
    privileged: true
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/video0:/dev/video0"
      - "/dev/media0:/dev/media0"
    volumes:
      - "/proc/device-tree:/proc/device-tree:ro"
      - "/run/udev:/run/udev"
    ports:
      - "8080:8080"
    restart: unless-stopped
