version: '2.1'

services:
  camera-stream:
    build: ./camera-stream
    privileged: true
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm-cma:/dev/vcsm-cma"
      - "/dev/video0:/dev/video0"
      - "/dev/media0:/dev/media0"
      - "/dev/media1:/dev/media1"
      - "/dev/media2:/dev/media2"
    volumes:
      - "/run/udev:/run/udev"
    ports:
      - "8080:8080"
    restart: unless-stopped
